### PR TITLE
feat:core:#95

### PR DESCRIPTION
**Pull request by louis030195**
## Description

`Core` step towards

```py
results = (
  await embedbase
  .dataset(recipe_id, farm_id, user_id, locaton_id)
  .search(question, max_token=3000, ratio=[.7, .1, .1, .1])
)
```

## Related Issue

#95 

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/different-ai/embedbase/blob/main/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/different-ai/embedbase/blob/main/CONTRIBUTING.md) guide.

- [x] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by louis030195** [comment]
@hotkartoffel happy to receive feedback on how to best handle duplicate in this

example use case in tests:
image


Should we filter duplicate now or in a later version? (i.e. when the same data is present across multiple datasets of the same user)

**Comment by louis030195** [comment]
```py
results = (
  await embedbase
  .dataset(recipe_id, farm_id, user_id, locaton_id)
  .search(question, max_token=3000, ratio=[.7, .1, .1, .1])
)
```

or

```py
results = (
  await embedbase
  .dataset(recipe_id)
  .dataset(farm_id)
  .dataset(user_id)
  .dataset(locaton_id)
  .search(question)
  .limit(max_token=3000)
  .ratio([.7, .1, .1, .1])
)
```

or

```py
results = (
  await embedbase
  .dataset(recipe_id, farm_id, user_id, locaton_id)
  .search(question)
  .limit(max_token=3000)
  .ratio([.7, .1, .1, .1])
)
```

or

```py
results = (
  await embedbase
  .dataset(recipe_id, farm_id, user_id, locaton_id)
  .search(question)
  .limit(max_token=3000, ratio=[.7, .1, .1, .1])
)
```

or something else? (ask same for TS)

**Comment by louis030195** [comment]
imho should optimise UX for:
- least amount of string
- functional approach
- while maintaining all degrees of freedom (the right abstraction)

**Comment by ccomkhj** [comment]
Looking forward to this update! @louis030195

**Pull request closed without merging**
